# Generated by Django 5.2.4 on 2025-10-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productimage_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='未分类', max_length=50, null=True, verbose_name='商品分类'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='主图'),
        ),
    ]
