# Generated by Django 5.2.4 on 2025-10-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_category_product_image_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='详细信息(JSON)'),
        ),
    ]
