# Generated by Django 5.2.4 on 2025-10-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_detail_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=20, verbose_name='价格'),
        ),
    ]
